package de.cinebuddy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservierungAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservierungAllPropertiesEquals(Reservierung expected, Reservierung actual) {
        assertReservierungAutoGeneratedPropertiesEquals(expected, actual);
        assertReservierungAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservierungAllUpdatablePropertiesEquals(Reservierung expected, Reservierung actual) {
        assertReservierungUpdatableFieldsEquals(expected, actual);
        assertReservierungUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservierungAutoGeneratedPropertiesEquals(Reservierung expected, Reservierung actual) {
        assertThat(actual)
            .as("Verify Reservierung auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservierungUpdatableFieldsEquals(Reservierung expected, Reservierung actual) {
        assertThat(actual)
            .as("Verify Reservierung relevant properties")
            .satisfies(a -> assertThat(a.getKundeName()).as("check kundeName").isEqualTo(expected.getKundeName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservierungUpdatableRelationshipsEquals(Reservierung expected, Reservierung actual) {
        assertThat(actual)
            .as("Verify Reservierung relationships")
            .satisfies(a -> assertThat(a.getPlaetzes()).as("check plaetzes").isEqualTo(expected.getPlaetzes()))
            .satisfies(a -> assertThat(a.getVorfuehrung()).as("check vorfuehrung").isEqualTo(expected.getVorfuehrung()));
    }
}
