package de.cinebuddy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SaalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaalAllPropertiesEquals(Saal expected, Saal actual) {
        assertSaalAutoGeneratedPropertiesEquals(expected, actual);
        assertSaalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaalAllUpdatablePropertiesEquals(Saal expected, Saal actual) {
        assertSaalUpdatableFieldsEquals(expected, actual);
        assertSaalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaalAutoGeneratedPropertiesEquals(Saal expected, Saal actual) {
        assertThat(actual)
            .as("Verify Saal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaalUpdatableFieldsEquals(Saal expected, Saal actual) {
        assertThat(actual)
            .as("Verify Saal relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getKapazitaet()).as("check kapazitaet").isEqualTo(expected.getKapazitaet()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaalUpdatableRelationshipsEquals(Saal expected, Saal actual) {
        // empty method
    }
}
