package de.cinebuddy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SitzplatzAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitzplatzAllPropertiesEquals(Sitzplatz expected, Sitzplatz actual) {
        assertSitzplatzAutoGeneratedPropertiesEquals(expected, actual);
        assertSitzplatzAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitzplatzAllUpdatablePropertiesEquals(Sitzplatz expected, Sitzplatz actual) {
        assertSitzplatzUpdatableFieldsEquals(expected, actual);
        assertSitzplatzUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitzplatzAutoGeneratedPropertiesEquals(Sitzplatz expected, Sitzplatz actual) {
        assertThat(actual)
            .as("Verify Sitzplatz auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitzplatzUpdatableFieldsEquals(Sitzplatz expected, Sitzplatz actual) {
        assertThat(actual)
            .as("Verify Sitzplatz relevant properties")
            .satisfies(a -> assertThat(a.getReihe()).as("check reihe").isEqualTo(expected.getReihe()))
            .satisfies(a -> assertThat(a.getNummer()).as("check nummer").isEqualTo(expected.getNummer()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitzplatzUpdatableRelationshipsEquals(Sitzplatz expected, Sitzplatz actual) {
        assertThat(actual)
            .as("Verify Sitzplatz relationships")
            .satisfies(a -> assertThat(a.getSaal()).as("check saal").isEqualTo(expected.getSaal()))
            .satisfies(a -> assertThat(a.getReservierungens()).as("check reservierungens").isEqualTo(expected.getReservierungens()));
    }
}
