package de.cinebuddy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VorfuehrungAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVorfuehrungAllPropertiesEquals(Vorfuehrung expected, Vorfuehrung actual) {
        assertVorfuehrungAutoGeneratedPropertiesEquals(expected, actual);
        assertVorfuehrungAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVorfuehrungAllUpdatablePropertiesEquals(Vorfuehrung expected, Vorfuehrung actual) {
        assertVorfuehrungUpdatableFieldsEquals(expected, actual);
        assertVorfuehrungUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVorfuehrungAutoGeneratedPropertiesEquals(Vorfuehrung expected, Vorfuehrung actual) {
        assertThat(actual)
            .as("Verify Vorfuehrung auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVorfuehrungUpdatableFieldsEquals(Vorfuehrung expected, Vorfuehrung actual) {
        assertThat(actual)
            .as("Verify Vorfuehrung relevant properties")
            .satisfies(a -> assertThat(a.getFilmTitel()).as("check filmTitel").isEqualTo(expected.getFilmTitel()))
            .satisfies(a -> assertThat(a.getDatumZeit()).as("check datumZeit").isEqualTo(expected.getDatumZeit()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVorfuehrungUpdatableRelationshipsEquals(Vorfuehrung expected, Vorfuehrung actual) {
        assertThat(actual)
            .as("Verify Vorfuehrung relationships")
            .satisfies(a -> assertThat(a.getSaal()).as("check saal").isEqualTo(expected.getSaal()));
    }
}
